workspace(name = "example_http_archive_locked_constrained")

local_repository(
    name = "bazel_lock",
    path = "..",
)

load("@bazel_lock//rules:locked.bzl", "git_repository")
load("//:LOCKFILE.bzl", "locked")

git_repository(
    name = "bazel_skylib",
    locked = locked,
    remote = "https://github.com/bazelbuild/bazel-skylib.git",
    upgrade_constraint = "~=0.8",
)

load("@bazel_skylib//lib:versions.bzl", "versions")

# Not an actual requirement. This is only to demonstrate usage of git_repository
versions.check(minimum_bazel_version = "1.0.0")
