workspace(name = "example_with_http_archive")

local_repository(
    name = "bazel_upgrade",
    path = "..",
)

load("@bazel_upgrade//rules:fetch.bzl", "http_archive")
load("//:LOCKFILE.bzl", "locked")

http_archive(
    name = "bazel_skylib",
    locked = locked,
    type = "tar.gz",
    url = "https://github.com/bazelbuild/bazel-skylib/releases/download/0.8.0/bazel-skylib.0.8.0.tar.gz",
)

load("@bazel_skylib//lib:versions.bzl", "versions")

# Not an actual requirement. This is only to demonstrate usage of http_archive
versions.check(minimum_bazel_version = "1.0.0")
