workspace(name = "example_with_http_archive")

local_repository(
    name = "bazel_upgrade",
    path = "..",
)

load("@bazel_upgrade//rules:upgrade.bzl", "http_archive")
load("//:LOCKFILE.bzl", "locked")

http_archive(
    name = "bazel_skylib",
    locked = locked,
    pin = "0.8.0",
    pin_url = "https://github.com/bazelbuild/bazel-skylib/releases/download/<pin>/bazel-skylib.<pin>.tar.gz",
    type = "tar.gz",
)

load("@bazel_skylib//lib:versions.bzl", "versions")

# Not an actual requirement. This is only to demonstrate usage of http_archive
versions.check(minimum_bazel_version = "1.0.0")
