on: push
name: Tests

jobs:
  test_on_ubuntu:
    name: RUN TESTS ON ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd example_http_archive_bare && bazelisk run hello
    - run: cd example_http_archive_locked && bazelisk run hello
    - run: cd example_git_repository_bare && bazelisk run hello
    - run: cd example_git_repository_locked && bazelisk run hello

  test_on_macos:
    name: RUN TESTS ON macos
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd example_http_archive_bare && bazelisk run hello
    - run: cd example_http_archive_locked && bazelisk run hello
    - run: cd example_git_repository_bare && bazelisk run hello
    - run: cd example_git_repository_locked && bazelisk run hello

  test_on_windows:
    name: RUN TESTS ON windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd example_http_archive_bare && bazelisk run hello
    - run: cd example_http_archive_locked && bazelisk run hello
    - run: cd example_git_repository_bare && bazelisk run hello
    - run: cd example_git_repository_locked && bazelisk run hello
